---
- name: Base setup for all hosts
  hosts: all
  become: yes
  roles:
    - { role: 'common', tags: 'common' }

- name: App/DB setup
  hosts: appserver
  become: yes
  roles:
    - { role: 'postgres', tags: 'postgres' }


