---
- name: Install netdata
  apt:
    name: netdata
    update-cache: yes

- name: Configure Netdata
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    mode: u=wrx,g=rx,o=r,+x
  notify: Restart Netdata

- name: Add health check notifications for Netdata
  template:
    src: health_alarm_notify.conf.j2
    dest: /etc/netdata/health_alarm_notify.conf
    mode: u=wrx,g=rx,o=r,+x
  notify: Restart Netdata

- name: Disable Netdata telemetry
  file:
    path: /etc/netdata/.opt-out-from-anonymous-statistics
    mode: u=wrx,g=r,o=r
    state: touch
