---
- name: Pre-seed domain name for Postfix
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ ansible_fqdn }}"
    vtype: text

- name: Pre-seed mailer type for postfix
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: Internet Site
    vtype: select

- name: Pre-seed alias for postfix
  debconf:
    name: postfix
    question: postfix/root_address
    value: "{{ recipient_email }}"
    vtype: text

- name: Install Postfix
  apt:
    update-cache: yes
    pkg:
      - mailutils
      - postfix

- name: Configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces'
    line: inet_interfaces = loopback-only
  notify:
    - Restart postfix
