---
- name: Upgrade system
  apt:
    update-cache: yes
    upgrade: yes

- name: Install base packages
  apt:
    pkg:
      - gpg
      - htop
      - ncurses-term
      - zsh
      - zstd

- name: Set defaults for bash
  blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    block: |
      shopt -s autocd
      set -o vi
      bind '"\e[A": history-search-backward'
      bind '"\e[B": history-search-forward'
      alias l="ls -a --color"
      alias ll="ls -lh --color"
      alias s!="sudo"
      alias v="vim"

- name: sshd configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
  notify:
    - Restart sshd

- include: unattended-upgrades.yml
