---
- name: Approve oldstable repo
  command: apt-get update -y --allow-releaseinfo-change

- name: Upgrade system
  apt:
    upgrade: yes

- name: Install base packages
  apt:
    pkg:
      - apt-listchanges
      - debconf-utils
      - gpg
      - htop
      - ncurses-term
      - unattended-upgrades
      - zsh
      - zstd

- name: Configure unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//Unattended-Upgrade::Mail '
    line: "Unattended-Upgrade::Mail {{ recipient_email }};"

- name: Set defaults for bash
  blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    block: |
      shopt -s autocd
      set -o vi
      bind '"\e[A": history-search-backward'
      bind '"\e[B": history-search-forward'
      alias l="ls -a --color"
      alias ll="ls -lh --color"
      alias s!="sudo"
      alias v="vim"

- name: sshd configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?ChallengeResponseAuthentication', line: 'ChallengeResponseAuthentication no' }
  notify:
    - Restart sshd
