---
- name: Create app user
  become_user: postgres
  postgresql_user:
    name: "{{ pg_user }}"
    password: "md515fef2b9ecf269085786d46bc504ee77"
    conn_limit: 5
    role_attr_flags: CREATEDB,LOGIN

- name: Create app DB in postgres
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    owner: "{{ pg_user }}"
