---
- name: Create data directory for Postgres
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: postgres
    group: postgres
    recurse: yes

- name: Check current Postgres cluster
  command: pg_lsclusters -h -j
  register: pg_cluster_chk
  ignore_errors: true
  changed_when: false

- name: Create Postgres cluster
  shell: |
    pg_dropcluster --stop 13 main

    pg_createcluster -d {{ data_dir }} --start 13 main \
      -o listen_addresses='*' \
      -o password_encryption=scram-sha-256 \
      -o shared_buffers=1GB \
      -o effective_cache_size=2GB \
      -o work_mem=32MB
  args:
    executable: /bin/bash
  when: (pg_cluster_chk.stdout | from_json | first)["pgdata"] != data_dir|string

- name: Create default user
  become_user: postgres
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ lookup('community.general.passwordstore', 'dev/mfa-pg create=true') }}"
    conn_limit: 5
    role_attr_flags: CREATEDB,LOGIN

- name: Create app DB in postgres
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    owner: "{{ pg_user }}"

- name: Configure access for default user
  postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    address: samenet
    contype: host
    databases: "{{ db_name }}"
    method: scram-sha-256
    users: "{{ pg_user }}"
