name: lint
on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup pip
        uses: actions/setup-python@v2

      - name: Install ansible & ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Terraform check
        run: |
          terraform fmt -check
          terraform validate -no-color

      - name: Ansible check
        run: |
          ansible-playbook --syntax-check site.yml
          ansible-lint --nocolor site.yml
